name: headunit_app
description: Interfaccia head unit (flutter-pi)
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
