listener 1883
protocol mqtt

listener 9001
protocol websockets

# Per uno sviluppo rapido va bene, ma in produzione attiva autenticazione:
# password_file /mosquitto/config/passwd
# acl_file /mosquitto/config/acl.conf
allow_anonymous true

persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
